### ISSUE TITLE
[solved] fatal error: 'tr1/functional' file not found

### ISSUE THREAD

**Issue by iassael** [HPCE/hpce-2014-cw4#1]
I am on Mac with gcc49 through homebrew and I was receiving this error when trying to compile the simple case:
`include/CL/cl.hpp:191:10: fatal error: 'tr1/functional' file not found`

The reason is that the TR1 experimental libraries were not included in the standard distribution.

I managed to solve it by updating `include/CL/cl.hpp` with a slightly newer version from:
`https://www.khronos.org/registry/cl/api/1.1/cl.hpp`.

Hopefully there will be no backwards compatibility errors.

**Comment by m8pple** [comment]
Ah, thanks. I think I'll update the cl.hpp with the version you suggest, as we're a ways beyond
C++11 TR these days.

Trying to maintain compatibility with providers who only provide OpenCL 1.1 has meant the
code is a bit stuck in the past, but as far as I'm aware NVidia still don't really support OpenCL 1.2.
